export const APP_VERIFIED_HEIGHT = 'APP_VERIFIED_HEIGHT'
export const APP_VERIFIED_WINDOW_ID = 'APP_VERIFIED_WINDOW_ID'

export const PHALA_CHAIN_NAME = 'PHALA_CHAIN_NAME'

export const EVENTS_STORAGE_KEY = 'EVENTS_STORAGE_KEY'
export const GRANDPA_AUTHORITIES_KEY = ':grandpa_authorities'
